# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

#Github Pages site and baseurl, uncomment this when deploying code to github
url:                #https://aisle5oakland.github.io
baseurl:            #/

#Local site, uncomment this for local testing
url:                http://localhost:4000

# Where things are - include submodule in path
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes

# Collections
collections:
  beermenu:
    output: true
  foodmenu:
    output: true
  nav_links:
    output: true



# Front Matter defaults
defaults:
  - scope:
      path: ""
      type: "posts" 
    values:
      layout: "post"

#Google Analytics tracking id
analytics: UA-88006909-1      

author:
  name:           'You Name'
  twitter:        https://twitter.com/yourtwitterhandle

gems:             [jekyll-paginate, jekyll-gist]
