# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Project Name
description:      'This is where you put your project short description'

#Github Pages site and baseurl, submodule name
url:                https://aisle5oakland.github.io
baseurl:            /

#Local site
url:                #http://localhost:4000

# Where things are - include submodule in path
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts" 
    values:
      layout: "post"

#Google Analytics tracking id
analytics:        

author:
  name:           'You Name'
  twitter:        https://twitter.com/yourtwitterhandle

gems:             [jekyll-paginate, jekyll-gist]
